### ISSUE TITLE
Can not installMaterial: QMM with blender 3.0.1

### ISSUE THREAD

**Issue by hgalt** [don1138/blender-qmm#1]
Blender doesn't install me the latest QMM version. If I try to install it by hand, I got the following error message, if I try to enable the add-on:
![grafik](https://user-images.githubusercontent.com/6670160/156939371-448f3f01-eedb-40e7-9eb1-eab6ab4a034f.png)

**Comment by don1138** [comment]
Hi - I just noticed that this issue has been added.

I remember seeing a note that there can be conflicts when `addon_updater` settings have the same name in different add-ons, and it looks like that's the case for you.

Are you still unable to activate QMM since you posted this?

I'm having other issues with the `addon_updater` and am considering removing it. If you are continuing to have problems, that may give me a good reason to do that.

**Comment by don1138** [comment]
I've been having enough trouble with the addon updater to warrant dumbing it down.

As of version 1.4.4, it will only allow manual download of the addon files.

If you're still having problems, let me know, but in the meantime, I'll mark this as closed.
