### ISSUE TITLE
Noble Metals dont seem to be setup correctly

### ISSUE THREAD

**Issue by schroef** [don1138/blender-qmm#4]
bl 283
osx 10.11.6

Im testing this on a old bl 2.83, so perhaps thats why. I dont get errors when adding the actual materials. But i noticed the gold, doesnt have metallic enabled, its also totally different setup vs the Gold Fresnel. Did you check all the materials how they look?

![Screen Shot 2022-10-28 at 14 52 43](https://user-images.githubusercontent.com/6923008/198711011-13df55e6-19c2-45e1-9071-5ad476d6a3ef.png)

also notice how Specular is connected wrong, its connect to roughness. If switch it, it does look better. But its still no metallic

**Comment by schroef** [comment]
Seems your defining the attributes wrong or this is bl 3.0 method. dont think it is. But trying to set metallic and other values by using a name wont work

![Screen Shot 2022-10-28 at 15 00 40](https://user-images.githubusercontent.com/6923008/198712532-e345b89e-3c8e-453c-b1a9-af73e613f19e.png)

**Comment by don1138** [comment]
1. The add-on has required **Blender 3.0** or later since version **1.3.0**.  That's why the `bl_info` is set to `"blender": (3, 0, 0)`, and the featured image is labeled "**Add-On for Blender 3.0+**". 😉

If you want to edit the code and make it **Blender 2.83** compatible, change the **BSDF** inputs from
```
# BLENDER 3.0
BSDF.inputs[6].default_value = # Metallic Value
BSDF.inputs[9].default_value = # Specular Value
BSDF.inputs[16].default_value = # IOR Value
```
to
```
# BLENDER 2.8.3
BSDF.inputs[4].default_value = # Metallic Value
BSDF.inputs[7].default_value = # Specular Value
BSDF.inputs[14].default_value = # IOR Value
```

2. The code in your screenshot is used to set the **Viewport Display** and has no effect on the rendered material.

3. The **Gold**, **Silver**, and **Copper** are created using different methods than **Gold Fresnel**, **Silver Fresnel**, and **Copper Fresnel**.

I keep the **Fresnel** materials in the add-on for sake of their uniqueness, and because they're useful for studying. I may remove them at some point. Probably when **Blender** materials get native **Energy Conservation**.

If you'd like to review their setup, the tutorials I followed to make both kinds are listed on the [Sources page in the Wiki](https://github.com/don1138/blender-qmm/wiki/Sources) under **The original inspiration**.

**Comment by schroef** [comment]
> 1. The add-on has required **Blender 3.0** or later since version **1.3.0**.  That's why the `bl_info` is set to `"blender": (3, 0, 0)`, and the featured image is labeled "**Add-On for Blender 3.0+**". 😉
> 
> If you want to edit the code and make it **Blender 2.83** compatible, change the **BSDF** inputs from
> 
> ```
> # BLENDER 3.0
> BSDF.inputs[6].default_value = # Metallic Value
> BSDF.inputs[9].default_value = # Specular Value
> BSDF.inputs[16].default_value = # IOR Value
> ```
> 
> to
> 
> ```
> # BLENDER 2.8.3
> BSDF.inputs[4].default_value = # Metallic Value
> BSDF.inputs[7].default_value = # Specular Value
> BSDF.inputs[14].default_value = # IOR Value
> ```
> 
> 2. The code in your screenshot is used to set the **Viewport Display** and has no effect on the rendered material.
> 3. The **Gold**, **Silver**, and **Copper** are created using different methods than **Gold Fresnel**, **Silver Fresnel**, and **Copper Fresnel**.
> 
> I keep the **Fresnel** materials in the add-on for sake of their uniqueness, and because they're useful for studying. I may remove them at some point. Probably when **Blender** materials get native **Energy Conservation**.
> 
> If you'd like to review their setup, the tutorials I followed to make both kinds are listed on the [Sources page in the Wiki](https://github.com/don1138/blender-qmm/wiki/Sources) under **The original inspiration**.

I know that, but i did not use the asset manager part, i did not see any code which will not run in bl 2.83
I did check it now at home with 3.3 and works as you state. Nice work! 
So they have added props to the material display now, i see more items being exposed under material
